### ISSUE TITLE
Discussion for CRAN release: 0.3.5

### ISSUE THREAD

**Issue by ijlyttle** [r-box/boxr#87]
I also have a project open for this, but I find that an issue can be useful for discussing stuff:

Technical issues to sort out (could still add some):

- [x] Testing #76
- [x] documentation -> RMarkdown #75 
- [x] pkgdown #77 
- [x] box ID integer/character #80
- [x] merge PR #105 
- [x] finish "rough" documentation #114 
- [x] make a preview release of the pkgdown site, so the README links will work #129
- [x] clean up {rio} #130 
- [x] make some API calls insistent #131 
- [x] polish documentation #132

CRAN checklist:

- [x] check NEWS (add item for auth-retry)
- [x] update README.md
- [x] create a `cran-release` branch 
- [x] version -> 0.3.5,  make sure version numbers align in NEWS and DESCRIPTION
- [x] r-hub checks 
- [x] update `cran-release` README to reflect cran installation instructions
- [x] update pkgdown badge to "cran-released"
- [x] submit, 🙏

upon acceptance:

- [x] merge into `master`
- [x] apply release tag
- [x] bump to development version in NEWS and DESCRIPTION

**Comment by ijlyttle** [comment]
Hi again @nathancday -

I'm getting back into the swing of things (finally). Here's my idea for ambitions for 3.5.0:

- update authorization - both refactoring the existing `box_auth()` and integrating your JWT work.
- automate testing (gargle idea)
- update and harmonize documentation on existing functions, changing functions themselves only if there is a compelling reason.

As it stands, we still need for and updated rio to go to CRAN - if we get to this point, and it hasn't, we might be able to make some workarounds here (but I'd rather avoid having to do that).

What do you think?

**Comment by ijlyttle** [comment]
Getting there...

**Comment by ijlyttle** [comment]
At last...
